Source/MrKupido.WebCore/Controllers/ImportController.cs
using MrKupido.DataAccess;
using MrKupido.Library;
using MrKupido.Model;
using MrKupido.Processor;
using MrKupido.Processor.Model;
using MrKupido.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace MrKupido.Web.Controllers
{
    public class ImportController : BaseController
    {
        private static MrKupidoContext db = new MrKupidoContext("Name=MrKupidoContext");
        private static char[] whiteSpaces = new char[] { ' ', ',', '.', '!', '?', ')', '(', '"', '&', ';', '\'', '[', ']', ':', '\\', '_', '`', '„', '<', '>', '\r', '\n', '”' };

        [Authorize]
        public IActionResult RecipeList()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LoadImportedRecipes(string langISO)
        {
            List<ImportedRecipe> recipes = null;
            if (langISO == "hun")
            {
                recipes = db.ImportedRecipes.Where(rec => (rec.UploadedOn < new DateTime(2011, 01, 01)) && (rec.Favourited > 500) && (rec.Rating >= 5) && (rec.Language == langISO)).OrderByDescending(rec => rec.Favourited + rec.Forwarded).Take(110).ToList();
            }
            if (langISO == "eng")
            {
                recipes = db.ImportedRecipes.Where(rec => (rec.ReviewCount > 500) && (rec.Rating >= 4) && (rec.Language == langISO)).OrderByDescending(rec => rec.Rating + (rec.ReviewCount / 1000000)).Take(110).ToList();
            }
            return PartialView("_ImportedRecipeList", recipes);
        }

        [Authorize]
        public IActionResult Recipe(string id)
        {
            var language = HttpContext.Session.GetString("Language");
            ImportedRecipe importedRecipe = db.ImportedRecipes.FirstOrDefault(r => (r.UniqueName == id) && (r.Language == language));
            if (importedRecipe == null) return RedirectToAction("Index", "HomeController");
            DataContractJsonSerializer dcjs = new DataContractJsonSerializer(typeof(string[]));
            // Ingredients
            List<string> ingredientList = new List<string>();
            ingredientList.AddRange(dcjs.ReadObject(new MemoryStream(Encoding.UTF8.GetBytes(importedRecipe.Ingredients))) as string[]);
            StringBuilder ingredients = new StringBuilder();
            foreach (string ingredient in ingredientList)
            {
                ingredients.AppendLine(ingredient.Trim());
            }
            // Original directions
            List<string> originalDirections = new List<string>();
            originalDirections.AddRange(dcjs.ReadObject(new MemoryStream(Encoding.UTF8.GetBytes(HttpUtility.HtmlDecode(importedRecipe.OriginalDirections)))) as string[]);
            // Directions
            List<string> directions = new List<string>();
            directions.AddRange(dcjs.ReadObject(new MemoryStream(Encoding.UTF8.GetBytes(HttpUtility.HtmlDecode(importedRecipe.Directions)))) as string[]);
            List<string> directionList = new List<string>();
            foreach (string direction in directions)
            {
                string[] dirs = direction.Split(new char[] { ',', '.' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (string dir in dirs)
                {
                    if (!String.IsNullOrWhiteSpace(dir)) directionList.Add(dir);
                }
            }
            return View(new object[] { importedRecipe, ingredients.ToString(), originalDirections, directionList });
        }

        [HttpPost]
        public ActionResult LoadIngredientTable(string langISO, string ingredients)
        {
            List<IngredientAmount> result = new List<IngredientAmount>();

            foreach (string text in ingredients.Split(new string[] { "\n" }, StringSplitOptions.RemoveEmptyEntries))
            {
                IngredientAmount ingredient = IngredientAmount.FromString(text);
                if (ingredient != null)
                {
                    ingredient.Language = langISO;

                    TreeNode tn = Cache.Ingredient[ingredient.IngredientName];
                    if (tn == null)
                    {
                        tn = Cache.Recipe[ingredient.IngredientName];
                    }
                    //Ingredient dbIngredient = db.Ingredients.Where(ing => ((ingredient.Language == "hun") && (ing.UniqueNameHun == ingredient.IngredientUniqueName)) || ((ingredient.Language == "eng") && (ing.UniqueNameEng == ingredient.IngredientUniqueName))).FirstOrDefault();
                    //ingredient.Index = (dbIngredient != null ? dbIngredient.Index.Value : -1);
                    ingredient.Index = (tn == null ? -1 : 1);

                    result.Add(ingredient);
                }
                else
                {
                    result.Add(new IngredientAmount());
                }
            }

            return PartialView("_IngredientTable", result.ToArray());
        }

        [HttpPost]
        public ActionResult MakeDirectionsBasic(string langISO, string directions)
        {
            StringBuilder result = new StringBuilder();
            bool isHtmlTag = false;
            directions = System.Net.WebUtility.HtmlDecode(directions);
            foreach (char d in directions.Replace("\n", "").Replace("</li>", "\n"))
            {
                if (d == '<') isHtmlTag = true;
                if (!isHtmlTag)
                {
                    result.Append(d);
                }
                else
                {
                    if (d == '>') isHtmlTag = false;
                }
            }
            string dirs = result.ToString();
            result.Clear();

            // NHunspell code commented out
            /*
            string culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.Replace("-", "_");
            string hunspellFilename = Path.GetFullPath(@".\" + culture + @"\") + culture;
            hunspellFilename = Server.MapPath(@"~\Content\spelling\" + culture + @"\") + culture;
            Hunspell hunspell = new Hunspell(hunspellFilename + ".aff", hunspellFilename + ".dic");
            */

            foreach (string dir in dirs.ToString().Split(new char[] { '\n' }, StringSplitOptions.RemoveEmptyEntries))
            {
                foreach (string word in dir.Split(whiteSpaces, StringSplitOptions.RemoveEmptyEntries))
                {
                    result.Append(" ");
                    string w = word.Trim();
                    float r;
                    bool isNumber = Single.TryParse(w, out r);
                    //bool correct = hunspell.Spell(w);
                    bool correct = true; // stub
                    if ((!correct) || (isNumber))
                    {
                        result.Append(w);
                        continue;
                    }
                    try
                    {
                        //List<string> stems = hunspell.Stem(w);
                        //result.Append(stems[0]);
                        result.Append(w); // stub
                    }
                    catch
                    {
                        result.Append(w);
                    }
                }
                result.Append('\n');
            }
            return PartialView("_BasicRecipe", result.ToString().Split(new char[] { '\n' }, StringSplitOptions.RemoveEmptyEntries));
        }

        [HttpPost]
        public ActionResult CreateIngredient(string nameHun, string uniqueNameHun, string nameEng, string uniqueNameEng)
        {
            throw new MrKupidoException("This function is not supported any more.");
        }

        [HttpPost]
        public ActionResult LoadRecipeKeywords(string langISO, string directions)
        {
            //string[] verbs = new string[0];
            string[] conjunctions = new string[0];
            List<string> ingredients = new List<string>();
            string[] devices = new string[0];
            HashSet<string> aliases = new HashSet<string>();
            string[] units = new string[0];

            if (langISO == "hun")
            {
                //verbs = new string[] { "meghamozni", "mosni", "megtisztitani", "szetszedni", "szetvalasztani", "keverni", "osszekeverni", "kemenyreverni", 
                //    "bekapcsolni", "belerakni", "varni", "talalni", "elomelegiteni", "berakni", "rarakni", "megfuttatni", "osszegyurni", "letakarni", 
                //    "homerseklet", "kiszaggatni", "nyujtani", "sodorni", "felkarikazni", "lereszelni", "rarakni", "belerakni", "raonteni", "beboritani", 
                //    "elomelegiteni", "eltavolitani", "felkockazni", "raszorni", "feldarabolni", "megforgatni", "raszorni", "lelocsolni", "levenni",
                //"megfozni", "preselni", "reszelni", "felverni", "megpuhitani", "megforgatni", "lecsepegtetni" };
                conjunctions = new string[] { "a", "az", "egy", "majd" };
                units = new string[] { "g", "dkg", "kg", "db", "ml", "cl", "dl", "l", "perc", "óra", "mm", "cm", "dm", "m", "fok" };
            }

            if (langISO == "eng")
            {
                // TODO
            }

            ingredients.AddRange(Cache.Ingredient.Indexer.All.Select(tn => tn.ShortName).ToArray());
            ingredients.AddRange(Cache.Recipe.Indexer.All.Select(tn => tn.ShortName).ToArray());
            devices = Cache.Equipment.Indexer.All.Select(tn => tn.ShortName).ToArray();

            List<string> verbs = new List<string>();
            foreach (EquipmentTreeNode etn in Cache.Equipment.Indexer.All)
            {
                foreach (EquipmentCommand ec in etn.ValidCommands)
                {
                    foreach (string name in ec.Names)
                    {
                        if (!verbs.Contains(name)) verbs.Add(name);

Source/MrKupido.WebCore/Controllers/IngredientController.cs
using MrKupido.Processor;
using MrKupido.Processor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace MrKupido.Web.Controllers
{
    public class IngredientController : BaseController
    {
        //[Authorize]
        public IActionResult Trees()
        {
            TreeNode[] result = new TreeNode[5];
            result[0] = TreeNode.BuildTree(Cache.Assemblies, t => new NatureTreeNode(t, HttpContext.Session.GetString("Language")), typeof(MrKupido.Library.Nature.NatureBase));
            result[1] = TreeNode.BuildTree(Cache.Assemblies, t => new IngredientTreeNode(t, HttpContext.Session.GetString("Language")), typeof(MrKupido.Library.Ingredient.IngredientBase));
            result[2] = TreeNode.BuildTree(Cache.Assemblies, t => new RecipeTreeNode(t, HttpContext.Session.GetString("Language")), typeof(MrKupido.Library.Recipe.RecipeBase));
            result[3] = TreeNode.BuildTree(Cache.Assemblies, t => new EquipmentTreeNode(t, HttpContext.Session.GetString("Language")), typeof(MrKupido.Library.Equipment.EquipmentBase));
            result[4] = TreeNode.BuildTree(Cache.Assemblies, t => new TagTreeNode(t, HttpContext.Session.GetString("Language")), typeof(MrKupido.Library.Tag.TagBase));

            ValidateIconUrls(result);

            return View(result);
        }

        private void ValidateIconUrls(TreeNode[] tns)
        {
            if (tns == null) return;

            foreach (TreeNode tn in tns)
            {
                ValidateIconUrls(tn.Children);
            }
        }
    }
}

Source/MrKupido.WebCore/Controllers/RecipeController.cs
using MrKupido.DataAccess;
using MrKupido.Library;
using MrKupido.Processor;
using MrKupido.Processor.Model;
using MrKupido.Utils;
using System;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace MrKupido.Web.Controllers
{
    public class RecipeController : BaseController
    {
        private MrKupidoContext db = new MrKupidoContext("Name=MrKupidoContext");

        //[Authorize]
        [HttpGet]
        public IActionResult Details(string id)
        {
            object[] result = new object[7];
            HttpContext.Session.Remove("SelectedRecipeId");
            RecipeTreeNode rtn = Cache.Recipe[id];
            var language = HttpContext.Session.GetString("Language");
            if (rtn == null)
            {
                return RedirectToRoute("Default", new { language = language, controller = "Home", action = "RecipeNotAvailableYet", lan = language, un = id });
            }
            HttpContext.Session.SetString("SelectedRecipeId", id);
            RuntimeIngredient[] ingredients = rtn.GetIngredients(1.0f, 4);
            foreach (RuntimeIngredient i in ingredients)
            {
                if (!String.IsNullOrEmpty(i.RecipeUniqueName) && String.IsNullOrEmpty(i.RecipeName))
                {
                    i.RecipeName = Cache.Recipe[i.RecipeUniqueName].ShortName;
                }
            }
            result[0] = rtn;
            result[1] = rtn.GetTags();
            result[2] = rtn.GetEquipment(1.0f, 4);
            result[3] = ingredients;
            result[4] = rtn.GetDirections(1.0f, 4);
            result[5] = rtn.GetNutritions(1.0f, 4);
            ValidateDirectionUrls((IDirection[])result[4]);
            return View(result);
        }

        private void ValidateDirectionUrls(IDirection[] directions)
        {
            foreach (RecipeDirection direction in directions)
            {
                if (direction.ActionIconUrl == null) direction.ActionIconUrl = PathUtils.GetAbsoluteUrlOfFirstExisting(rootUrl, direction.ActionIconUrls);
                foreach (RecipeDirectionSegment segment in direction.DirectionSegments)
                {
                    if (segment is RecipeDirectionSegmentReference)
                    {
                        RecipeDirectionSegmentReference rdsr = ((RecipeDirectionSegmentReference)segment);
                        if (String.IsNullOrEmpty(rdsr.IconUrl) && (rdsr.TreeNode != null) && ((rdsr.TreeNode is EquipmentTreeNode) || (rdsr.Reference is MrKupido.Library.Ingredient.IngredientGroup)))
                        {
                            rdsr.IconUrl = rdsr.TreeNode.GetIconUrl(rootUrl);
                        }
                        if (String.IsNullOrEmpty(rdsr.IconUrl)) continue;
                        rdsr.IconUrl = PathUtils.ConvertRelativeUrlToAbsoluteUrl(rootUrl, rdsr.IconUrl);
                    }
                }
            }
        }

        [HttpPost]
        public JsonResult GetNewStrings(float portion, int multiplier)
        {
            return Json(
                new string[] {
                    String.Format(MrKupido.Web.Resources.Recipe.Details.EquipmentMissing, 1),
                    String.Format(MrKupido.Web.Resources.Recipe.Details.PortionHint, multiplier),
                    MrKupido.Web.Resources.Recipe.Details.ChefNumberOne
                });
        }

        [HttpPost]
        public IActionResult GetIngredients(float portion, int multiplier)
        {
            portion = portion / 1000.0f;
            var selectedRecipeId = HttpContext.Session.GetString("SelectedRecipeId");
            RecipeTreeNode rtn = Cache.Recipe[selectedRecipeId];
            RuntimeIngredient[] ingredients = rtn.GetIngredients(portion, multiplier);
            foreach (RuntimeIngredient i in ingredients)
            {
                if (!String.IsNullOrEmpty(i.RecipeUniqueName) && String.IsNullOrEmpty(i.RecipeName))
                {
                    i.RecipeName = Cache.Recipe[i.RecipeUniqueName].ShortName;
                }
            }
            return PartialView("_RecipeIngredients", ingredients);
        }

        [HttpPost]
        public IActionResult GetDirections(float portion, int multiplier)
        {
            portion = portion / 1000.0f;
            var selectedRecipeId = HttpContext.Session.GetString("SelectedRecipeId");
            RecipeTreeNode rtn = Cache.Recipe[selectedRecipeId];
            IDirection[] dirs = rtn.GetDirections(portion, multiplier);
            ValidateDirectionUrls(dirs);
            return PartialView("_RecipeDirections", dirs);
        }
    }
}

Source/MrKupido.WebCore/Views/Import/Recipe.cshtml
@model object[]
@{
    ViewBag.Title = "Recept importálás - Mr. Kupido";
}
@using MrKupido.Web.Models
<script type="text/javascript">
     var uniqueName = '@(((MrKupido.Model.ImportedRecipe)Model[0]).UniqueName)';
     var $textChanged = false;
     $.ajaxSetup({
         type: 'POST',
         contentType: "application/json; charset=utf-8",
         dataType: 'html',
         cache: false
     });
     $(document).ready(function () {
         attachEventHandlerToIngredientList();
         $('textarea#ingredients').trigger('change');
         $('section#recipeeditor').trigger('keyup');
         $textChanged = false;
         $("div#confirmRecipeSave").on('dialogclose', function (event) {
             $('select#recipes').trigger('change');
         });
     });
     function attachEventHandlerToIngredientList() {
         $('textarea#ingredients').on('change.kupido', function () {
             $textChanged = true;
             $('textarea#ingredients').attr('disabled', 'disabled');
             $.ajax({
                 url: '../LoadIngredientTable',
                 data: JSON.stringify({ langISO: 'hun', ingredients: $('textarea#ingredients').val() }),
                 success: function (result) {
                     $('div#_IngredientTable').html(result);
                     $('textarea#ingredients').removeAttr('disabled');
                 }
             });
         });
     };
     function saveRecipe() {
         $('input#savebutton').attr('disabled', 'disabled');
         $.ajax({
             url: '@Url.Action("SaveRecipe", "Import")',
            data: JSON.stringify({ recipeUniqueName: uniqueName, ingredients: $('textarea#ingredients').val(), directions: $('section#recipeeditor').html() }),
            success: function (result) {
                $('input#savebutton').removeAttr('disabled');
            }
        });
    };
</script>
<header class="nosearch">
    <a href="~/">
        <img src="~/Content/svg/logo_mrkupido_wide.svg" alt="Mr. Kupido" width="600" height="157" />
    </a>
</header>
<hr class="double" />
<details id="importrecipe" open class="alwaysopen">
    <summary>
        <h1>Recept importálás</h1>
        <hr class="single" />
        <h3>
            @{ string name = ((MrKupido.Model.ImportedRecipe)Model[0]).DisplayName; }
            @name</h3>
        <hr class="single" />
    </summary>
</details>
<hr />
<details id="ingredientlist" class="boxed" open>
    <summary>
        <h1>1. Módosítsd a hozzávalók listáját</h1>
    </summary>
    <div id="_IngredientList">
        @await Html.PartialAsync("_IngredientList", Model[1])
    </div>
</details>
<hr />
<details id="ingredienttable" class="boxed" open>
    <summary>
        <h1>2. Ellenőrízd, hogy minden összetevő helyesen szerepel-e a táblában</h1>
    </summary>
    <div id="_IngredientTable">
        @await Html.PartialAsync("_IngredientTable", null)
    </div>
</details>
<hr />
<details id="originalrecipe" class="boxed" open>
    <summary>
        <h1>3. A recept eredeti szövege</h1>
    </summary>
    <div id="_OriginalRecipe">
        @await Html.PartialAsync("_OriginalRecipe", Model[2])
    </div>
</details>
<hr />
<details open>
    <summary>
        <h1>4. Ird át úgy a receptet, hogy ne legyen benne értelmezhetetlen kifejezés</h1>
    </summary>
    <div id="recipeeditor" class="boxed">
        <div id="_RecipeEditor">
            @await Html.PartialAsync("_RecipeEditor", Model[3])
        </div>
    </div>
    <div id="basicrecipe" class="boxed">
        <div id="_BasicRecipe">
            @await Html.PartialAsync("_BasicRecipe", null)
        </div>
    </div>
</details>
<hr />
<details id="recipecode" class="boxed" open>
    <summary>
        <h1>5. A generált programkód, amit be lehet illeszteni</h1>
    </summary>
    <div id="_RecipeCode">
        @await Html.PartialAsync("_RecipeCode", null)
    </div>
</details>
<hr />
<div class="formbuttons">
    <input id="savebutton" type="button" title="Save" value="Változások mentése" onclick="javascript: saveRecipe();" />
</div>

Source/MrKupido.WebCore/Views/Import/RecipeList.cshtml
@{
    ViewBag.Title = "Recept importálás - Mr. Kupido";
}
@using MrKupido.Web.Models
<script type="text/javascript">
    var $textChanged = false;
    var $prevRecipeUniqueName = "";
    var $recipeUniqueName = "";
    var $prevIngredients = "";
    var $ingredients = "";
    $.ajaxSetup({
        type: 'POST',
        contentType: "application/json; charset=utf-8",
        dataType: 'html',
        cache: false
    });
    $(document).ready(function () {
        $('select#language').on('change.kupido', function () {
            var langISO = $(this).val();
            $(this).attr('disabled', 'disabled');
            $.ajax({
                url: 'LoadImportedRecipes',
                data: JSON.stringify({ langISO: langISO }),
                success: function (result) {
                    $('div#_ImportedRecipeList').html(result);
                    $('select#language').removeAttr('disabled');
                    attachEventHandlerToImportedRecipeList();
                }
            });
        });
        $('select#language').trigger('change');
    });
</script>
<header class="nosearch">
    <a href="~/">
        <img src="~/Content/svg/logo_mrkupido_wide.svg" alt="Mr. Kupido" width="600" height="157" />
    </a>
</header>
<details id="chooserecipe" open class="alwaysopen">
    <summary>
        <h1>Recept importálás - recept kiválasztása</h1>
    </summary>
    <div id="languages" class="boxed">
        <h2>1. Válassz nyelvet</h2>
        <select id="language" autofocus>
            <option value="eng">English</option>
            <option value="hun">Hungarian</option>
        </select>
    </div>
    <div id="recipelist" class="boxed">
        <h2>2. Válassz receptet</h2>
        <div id="_ImportedRecipeList">
        </div>
    </div>
</details>

Source/MrKupido.WebCore/Views/Import/_BasicRecipe.cshtml
@model IEnumerable<string>
<section id="basicrecipe">
    <ol>
        @if (Model != null)
        {
            foreach (string item in Model)
            {
            <li>
                @foreach (string s in item.Split(new string[] { " ", "&nbsp;" }, StringSplitOptions.RemoveEmptyEntries))
                {
                    <span>@s</span>
                }
            </li>
            }
        }
    </ol>
</section>

Source/MrKupido.WebCore/Views/Import/_ImportedRecipeList.cshtml
@model IEnumerable<MrKupido.Model.ImportedRecipe>

@foreach (MrKupido.Model.ImportedRecipe item in Model)
{
    <a href="./Recipe/@item.UniqueName">@item.DisplayName</a><br />
}

Source/MrKupido.WebCore/Views/Import/_IngredientTable.cshtml
@model IEnumerable<MrKupido.Model.IngredientAmount>
@using MrKupido.Web.Models
<script type="text/javascript">
    $(function () {
        $("a.add").click(function (event) {
            event.preventDefault();
            $("div#createIngredient_" + $(this).attr('href')).dialog("open");
        });
        $("div.createIngredient").dialog({ modal: true, resizable: false, autoOpen: false, buttons: [
            {
                text: "Save",
                click: function () {
                    $(this).dialog("option", "title", "Mentés folyamatban...");
                    var index = $(this).children("input.index").val();
                    $.ajax({
                        url: 'CreateIngredient',
                        data: JSON.stringify({
                            nameHun: $(this).children("input.nameHun").val(),
                            uniqueNameHun: $(this).children("input.uniqueNameHun").val(),
                            nameEng: $(this).children("input.nameEng").val(),
                            uniqueNameEng: $(this).children("input.uniqueNameEng").val()
                        }),
                        success: function (result) {
                            $("div#createIngredient_" + index).dialog("close");
                            $("div#createIngredient_" + index).dialog("option", "title", "Új hozzávaló hozzáadása");
                        }
                    });
                }
            },
            {
                text: "Cancel",
                click: function () { $(this).dialog("close"); }
            }
        ] });
    });
</script>
<table id="ingredienttable" class="wide">
    <thead>
        <tr>
            <th>Teljes szöveg</th>
            <th>Mennyiség</th>
            <th>Mértékegység</th>
            <th>Megnevezés</th>
            <th>Formátum</th>
            <th>Állapot</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            int i = 0;
            foreach (var item in Model)
            {
                i++;
            <tr>
                <td>@item.ToString()</td>
                <td>@Html.DisplayFor(modelItem => item.Amount)</td>
                <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                <td>@Html.DisplayFor(modelItem => item.IngredientName)</td>
                <td>@Html.DisplayFor(modelItem => item.Format)</td>
                <td>
                    <img src="~/Content/svg/circle_plus.svg" alt="Add" width="20" height="20" />
                </td>
            </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7">
                Összesen @(Model != null ? Model.Count() : 0) hozzávaló
            </td>
        </tr>
    </tfoot>
</table>